config:
  target: 'http://localhost:3000'
  phases:
    - duration: 60
      arrivalRate: 5
      rampTo: 10
      name: Warm up the API
    - duration: 60
      arrivalRate: 10
      rampTo: 50
      name: Ramp up to peak load
    - duration: 300
      arrivalRate: 50
      name: Sustained peak load
  plugins:
    metrics-by-endpoint: { }
    expect: { }
scenarios:
  - name: Home
    flow:
      - get:
          url: "/"
          expect:
            statusCode: 200